/**
 * Flare's app themes: ten themes, each with a light and a dark variant. A theme sets three
 * things together: the app's colours, the terminal's colours (an xterm.js TerminalTheme)
 * and its shape (type, corners, borders, shadows, glow). docs/design.md explains when to use
 * each token; the values come from the design system's tokens/themes.json.
 *
 * - colors: the tokens useTheme() returns. primaryText is the accent wherever it is text or
 *   an icon on a surface; primary stays for fills, borders, the cursor and focus. They are
 *   equal except where the accent is too light to read as text (Graphite's lime, Concrete's
 *   yellow).
 * - terminal: the terminal is the screen, so its background is the app's.
 * - shape: per theme. Fonts are faces from theme.ts's FontRoles, never fontWeight.
 *
 * The terminal palettes of the well-known themes are under permissive licences (credited in
 * README.md):
 *
 * - Tokyo Night: folke/tokyonight.nvim's terminal extras, Night and Day (Apache-2.0)
 * - Catppuccin: catppuccin/kitty, Mocha and Latte (MIT)
 * - Solarized: Ethan Schoonover's palette (MIT), with bright black lifted to base01 so dim
 *   text stays visible on the dark background
 * - Gruvbox: morhetz/gruvbox (MIT/X11), medium contrast
 */

import type { FontFace, TerminalTheme } from './theme';

export const APP_THEME_IDS = [
  'flare',
  'phosphor',
  'tokyo-night',
  'catppuccin',
  'gruvbox',
  'solarized',
  'graphite',
  'orbit',
  'neon',
  'concrete',
] as const;

export type AppThemeId = (typeof APP_THEME_IDS)[number];

export const DEFAULT_APP_THEME: AppThemeId = 'flare';

export type AppColors = {
  background: string;
  backgroundElement: string;
  backgroundSelected: string;
  backgroundRaised: string;
  border: string;
  text: string;
  textSecondary: string;
  primary: string;
  onPrimary: string;
  primaryMuted: string;
  primaryText: string;
  success: string;
  warning: string;
  danger: string;
  attention: string;
  shadow: string;
  keyboard: string;
  key: string;
  keyFunction: string;
  keyShadow: string;
  keyArmed: string;
  primaryBorder: string;
  segmentTrack: string;
  segmentThumb: string;
};

export type ThemeShape = {
  /** ui: everything people read. display: title, subtitle. label: overline. mono: machine text. */
  fonts: { ui: FontFace; display: FontFace; label: FontFace; mono: FontFace };
  displayWeight: 400 | 500 | 600 | 700;
  /** letterSpacing for title/subtitle. */
  displayTracking: number;
  displayCase: 'none' | 'uppercase';
  labelCase: 'none' | 'uppercase';
  labelTracking: number;
  labelWeight: 400 | 500 | 600 | 700;
  /** Corners. key: the keyboard's keys; dot: status lights (0 = square). */
  radius: { small: number; medium: number; large: number; pill: number; key: number; dot: number };
  /** Cards, fields, rows and tabs; 1 means a hairline. */
  borderWidth: number;
  /** Selected picker tile. */
  borderWidthStrong: number;
  /** boxShadow strings ('none' = omit). */
  shadowCard: string;
  shadowFloat: string;
  shadowControl: string;
  /** Extra boxShadow on primary fills, the cursor and the live underline. */
  glowPrimary: string;
  /** Wordmark + display text glow (textShadowColor/Radius), or null. */
  textGlow: { color: string; radius: number } | null;
  /** Pressed: scale, and translate (Concrete presses into its hard shadow). */
  pressScale: number;
  pressShift: number;
  /** The Material Symbols cut the design names (not drawn yet: expo-symbols has one cut). */
  iconStyle: 'outlined' | 'rounded' | 'sharp';
};

export type ThemeVariant = { colors: AppColors; terminal: TerminalTheme; shape: ThemeShape };
export type AppTheme = {
  id: AppThemeId;
  name: string;
  family: string;
  description: string;
  light: ThemeVariant;
  dark: ThemeVariant;
};

export const APP_THEMES: readonly AppTheme[] = [
  {
    id: 'flare',
    name: 'Flare',
    family: 'Signature',
    description: 'Ink and ember. The default: one warm accent on deep cool ink, warm paper by day.',
    dark: {
      colors: {
        background: '#0B0D10',
        backgroundElement: '#14171C',
        backgroundSelected: '#1E2229',
        backgroundRaised: '#22262D',
        border: '#252931',
        text: '#ECEEF1',
        textSecondary: '#9199A5',
        primary: '#FF8A3D',
        onPrimary: '#1B0E04',
        primaryMuted: '#2E1F15',
        primaryText: '#FF8A3D',
        success: '#3DD68C',
        warning: '#F2C14E',
        danger: '#FF6369',
        attention: '#FF8A3D',
        shadow: '#000000',
        keyboard: '#13151A',
        key: '#2C3038',
        keyFunction: '#1F2229',
        keyShadow: '#050608',
        keyArmed: '#3D2716',
        primaryBorder: 'transparent',
        segmentTrack: '#14171C',
        segmentThumb: '#22262D',
      },
      terminal: {
        background: '#0B0D10',
        foreground: '#D9DDE3',
        cursor: '#FF8A3D',
        cursorAccent: '#0B0D10',
        selectionBackground: '#FF8A3D40',
        black: '#2A2F37',
        red: '#FF6369',
        green: '#3DD68C',
        yellow: '#F2C14E',
        blue: '#6AA8FF',
        magenta: '#C792EA',
        cyan: '#4FD1D9',
        white: '#C9CED6',
        brightBlack: '#727B88',
        brightRed: '#FF8A8F',
        brightGreen: '#6EE7A8',
        brightYellow: '#FFD978',
        brightBlue: '#93C0FF',
        brightMagenta: '#E0B0FF',
        brightCyan: '#7FE5EB',
        brightWhite: '#F3F5F8',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.5,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 0.9,
        labelWeight: 600,
        radius: {
          small: 8,
          medium: 12,
          large: 16,
          pill: 999,
          key: 7,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(0, 0, 0, 0.6)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'outlined',
      },
    },
    light: {
      colors: {
        background: '#F6F5F3',
        backgroundElement: '#FFFFFF',
        backgroundSelected: '#ECE9E4',
        backgroundRaised: '#FFFFFF',
        border: '#E2DED8',
        text: '#1A1816',
        textSecondary: '#5F5952',
        primary: '#C2410C',
        onPrimary: '#FFFFFF',
        primaryMuted: '#FCEDE3',
        primaryText: '#C2410C',
        success: '#17803F',
        warning: '#8F5B00',
        danger: '#C9262E',
        attention: '#C2410C',
        shadow: '#2B2116',
        keyboard: '#E3DFD9',
        key: '#FFFFFF',
        keyFunction: '#D5D0C8',
        keyShadow: '#A39C92',
        keyArmed: '#FCEDE3',
        primaryBorder: 'transparent',
        segmentTrack: '#ECE9E4',
        segmentThumb: '#FFFFFF',
      },
      terminal: {
        background: '#F6F5F3',
        foreground: '#1F1D1A',
        cursor: '#D9480F',
        cursorAccent: '#F6F5F3',
        selectionBackground: '#E8590C33',
        black: '#1F1D1A',
        red: '#C9262E',
        green: '#16794A',
        yellow: '#8F5B00',
        blue: '#1F5FCC',
        magenta: '#9C3FC4',
        cyan: '#0E7C86',
        white: '#6F6A63',
        brightBlack: '#7F7971',
        brightRed: '#D7373E',
        brightGreen: '#138A50',
        brightYellow: '#9A6A00',
        brightBlue: '#2F6FE0',
        brightMagenta: '#A64ACF',
        brightCyan: '#0B8793',
        brightWhite: '#8A847C',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.5,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 0.9,
        labelWeight: 600,
        radius: {
          small: 8,
          medium: 12,
          large: 16,
          pill: 999,
          key: 7,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(43, 33, 22, 0.15)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'outlined',
      },
    },
  },
  {
    id: 'phosphor',
    name: 'Phosphor',
    family: 'Terminal',
    description:
      'A green CRT. Everything is monospace, the text glows faintly, and agents asking for you burn amber.',
    dark: {
      colors: {
        background: '#050A06',
        backgroundElement: '#0B140D',
        backgroundSelected: '#102016',
        backgroundRaised: '#142A1C',
        border: '#1A3322',
        text: '#A8F5B8',
        textSecondary: '#5FAE74',
        primary: '#39FF6A',
        onPrimary: '#031207',
        primaryMuted: '#0F2E19',
        primaryText: '#39FF6A',
        success: '#39FF6A',
        warning: '#FFD24A',
        danger: '#FF5A4F',
        attention: '#FFB000',
        shadow: '#000000',
        keyboard: '#030704',
        key: '#102016',
        keyFunction: '#0A150D',
        keyShadow: '#000000',
        keyArmed: '#1A3A22',
        primaryBorder: 'transparent',
        segmentTrack: '#0B140D',
        segmentThumb: '#142A1C',
      },
      terminal: {
        background: '#050A06',
        foreground: '#9CF5B0',
        cursor: '#39FF6A',
        cursorAccent: '#050A06',
        selectionBackground: '#39FF6A33',
        black: '#0F1F13',
        red: '#FF6B5E',
        green: '#39FF6A',
        yellow: '#FFD24A',
        blue: '#5AD1FF',
        magenta: '#D78BFF',
        cyan: '#4DFFD2',
        white: '#B7E8C2',
        brightBlack: '#4F7A5A',
        brightRed: '#FF9187',
        brightGreen: '#8CFFAA',
        brightYellow: '#FFE287',
        brightBlue: '#92E1FF',
        brightMagenta: '#E6B3FF',
        brightCyan: '#8FFFE4',
        brightWhite: '#E6FFEC',
      },
      shape: {
        fonts: {
          ui: 'geistMono',
          display: 'geistMono',
          label: 'geistMono',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -1,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 1.2,
        labelWeight: 600,
        radius: {
          small: 4,
          medium: 6,
          large: 8,
          pill: 4,
          key: 4,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(0, 0, 0, 0.6)',
        shadowControl: 'none',
        glowPrimary: '0 0 14px rgba(57, 255, 106, 0.35)',
        textGlow: {
          color: 'rgba(57, 255, 106, 0.45)',
          radius: 6,
        },
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'sharp',
      },
    },
    light: {
      colors: {
        background: '#F1F5EE',
        backgroundElement: '#FBFDF9',
        backgroundSelected: '#E2EADD',
        backgroundRaised: '#FFFFFF',
        border: '#CFDCC9',
        text: '#0E2A16',
        textSecondary: '#3F6249',
        primary: '#0F7A32',
        onPrimary: '#F1F5EE',
        primaryMuted: '#DCEFDF',
        primaryText: '#0F7A32',
        success: '#0F7A32',
        warning: '#8A5D00',
        danger: '#B3261E',
        attention: '#A55A00',
        shadow: '#0E2A16',
        keyboard: '#E2EADD',
        key: '#FBFDF9',
        keyFunction: '#CCD9C6',
        keyShadow: '#9AAE95',
        keyArmed: '#F4E3C7',
        primaryBorder: 'transparent',
        segmentTrack: '#E2EADD',
        segmentThumb: '#FBFDF9',
      },
      terminal: {
        background: '#F1F5EE',
        foreground: '#12331B',
        cursor: '#0F7A32',
        cursorAccent: '#F1F5EE',
        selectionBackground: '#0F7A3226',
        black: '#12331B',
        red: '#B3261E',
        green: '#0F7A32',
        yellow: '#8A5D00',
        blue: '#1D5FA8',
        magenta: '#8B3AA8',
        cyan: '#0B7A72',
        white: '#5F7466',
        brightBlack: '#6F8676',
        brightRed: '#C73A30',
        brightGreen: '#138A3C',
        brightYellow: '#9A6A00',
        brightBlue: '#2A6FBE',
        brightMagenta: '#9A4BB8',
        brightCyan: '#0E8A80',
        brightWhite: '#7D9184',
      },
      shape: {
        fonts: {
          ui: 'geistMono',
          display: 'geistMono',
          label: 'geistMono',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -1,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 1.2,
        labelWeight: 600,
        radius: {
          small: 4,
          medium: 6,
          large: 8,
          pill: 4,
          key: 4,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(43, 33, 22, 0.15)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'sharp',
      },
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    family: 'Terminal',
    description: 'folke/tokyonight Night and Day, carried from the terminal into the app.',
    dark: {
      colors: {
        background: '#1A1B26',
        backgroundElement: '#1F2335',
        backgroundSelected: '#292E42',
        backgroundRaised: '#2F3549',
        border: '#2F344A',
        text: '#C0CAF5',
        textSecondary: '#9AA5CE',
        primary: '#7AA2F7',
        onPrimary: '#15161E',
        primaryMuted: '#283457',
        primaryText: '#7AA2F7',
        success: '#9ECE6A',
        warning: '#E0AF68',
        danger: '#F7768E',
        attention: '#FF9E64',
        shadow: '#000000',
        keyboard: '#16161E',
        key: '#292E42',
        keyFunction: '#1F2335',
        keyShadow: '#0C0D14',
        keyArmed: '#283457',
        primaryBorder: 'transparent',
        segmentTrack: '#1F2335',
        segmentThumb: '#2F3549',
      },
      terminal: {
        background: '#1A1B26',
        foreground: '#C0CAF5',
        cursor: '#C0CAF5',
        cursorAccent: '#1A1B26',
        selectionBackground: '#283457',
        black: '#15161E',
        red: '#F7768E',
        green: '#9ECE6A',
        yellow: '#E0AF68',
        blue: '#7AA2F7',
        magenta: '#BB9AF7',
        cyan: '#7DCFFF',
        white: '#A9B1D6',
        brightBlack: '#414868',
        brightRed: '#FF899D',
        brightGreen: '#9FE044',
        brightYellow: '#FABA4A',
        brightBlue: '#8DB0FF',
        brightMagenta: '#C7A9FF',
        brightCyan: '#A4DAFF',
        brightWhite: '#C0CAF5',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.5,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 0.9,
        labelWeight: 600,
        radius: {
          small: 8,
          medium: 12,
          large: 16,
          pill: 999,
          key: 7,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(0, 0, 0, 0.6)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'outlined',
      },
    },
    light: {
      colors: {
        background: '#E1E2E7',
        backgroundElement: '#F4F5F8',
        backgroundSelected: '#D0D5E3',
        backgroundRaised: '#FFFFFF',
        border: '#C4C8DA',
        text: '#343B58',
        textSecondary: '#565D7E',
        primary: '#2E6AD9',
        onPrimary: '#FFFFFF',
        primaryMuted: '#DCE5F8',
        primaryText: '#295FC3',
        success: '#587539',
        warning: '#8C6C3E',
        danger: '#C31648',
        attention: '#994F00',
        shadow: '#343B58',
        keyboard: '#D0D5E3',
        key: '#F4F5F8',
        keyFunction: '#C1C7DA',
        keyShadow: '#9AA1BD',
        keyArmed: '#DCE5F8',
        primaryBorder: 'transparent',
        segmentTrack: '#D0D5E3',
        segmentThumb: '#F4F5F8',
      },
      terminal: {
        background: '#E1E2E7',
        foreground: '#3760BF',
        cursor: '#3760BF',
        cursorAccent: '#E1E2E7',
        selectionBackground: '#B7C1E3',
        black: '#B4B5B9',
        red: '#F52A65',
        green: '#587539',
        yellow: '#8C6C3E',
        blue: '#2E7DE9',
        magenta: '#9854F1',
        cyan: '#007197',
        white: '#6172B0',
        brightBlack: '#A1A6C5',
        brightRed: '#FF4774',
        brightGreen: '#5C8524',
        brightYellow: '#A27629',
        brightBlue: '#358AFF',
        brightMagenta: '#A463FF',
        brightCyan: '#007EA8',
        brightWhite: '#3760BF',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.5,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 0.9,
        labelWeight: 600,
        radius: {
          small: 8,
          medium: 12,
          large: 16,
          pill: 999,
          key: 7,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(43, 33, 22, 0.15)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'outlined',
      },
    },
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin',
    family: 'Terminal',
    description: 'Mocha and Latte: soft pastel on mauve-grey, peach for attention.',
    dark: {
      colors: {
        background: '#1E1E2E',
        backgroundElement: '#24243A',
        backgroundSelected: '#313244',
        backgroundRaised: '#363850',
        border: '#3A3B52',
        text: '#CDD6F4',
        textSecondary: '#A6ADC8',
        primary: '#CBA6F7',
        onPrimary: '#1E1E2E',
        primaryMuted: '#3B3150',
        primaryText: '#CBA6F7',
        success: '#A6E3A1',
        warning: '#F9E2AF',
        danger: '#F38BA8',
        attention: '#FAB387',
        shadow: '#11111B',
        keyboard: '#181825',
        key: '#313244',
        keyFunction: '#262637',
        keyShadow: '#11111B',
        keyArmed: '#3B3150',
        primaryBorder: 'transparent',
        segmentTrack: '#24243A',
        segmentThumb: '#363850',
      },
      terminal: {
        background: '#1E1E2E',
        foreground: '#CDD6F4',
        cursor: '#F5E0DC',
        cursorAccent: '#1E1E2E',
        selectionBackground: '#585B7099',
        black: '#45475A',
        red: '#F38BA8',
        green: '#A6E3A1',
        yellow: '#F9E2AF',
        blue: '#89B4FA',
        magenta: '#F5C2E7',
        cyan: '#94E2D5',
        white: '#BAC2DE',
        brightBlack: '#585B70',
        brightRed: '#F38BA8',
        brightGreen: '#A6E3A1',
        brightYellow: '#F9E2AF',
        brightBlue: '#89B4FA',
        brightMagenta: '#F5C2E7',
        brightCyan: '#94E2D5',
        brightWhite: '#A6ADC8',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.5,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 0.9,
        labelWeight: 600,
        radius: {
          small: 8,
          medium: 12,
          large: 16,
          pill: 999,
          key: 7,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(0, 0, 0, 0.6)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'rounded',
      },
    },
    light: {
      colors: {
        background: '#EFF1F5',
        backgroundElement: '#FFFFFF',
        backgroundSelected: '#E6E9EF',
        backgroundRaised: '#FFFFFF',
        border: '#CCD0DA',
        text: '#4C4F69',
        textSecondary: '#5C5F77',
        primary: '#8839EF',
        onPrimary: '#FFFFFF',
        primaryMuted: '#ECE2FC',
        primaryText: '#8839EF',
        success: '#2F7D1F',
        warning: '#A8650A',
        danger: '#D20F39',
        attention: '#BB4705',
        shadow: '#4C4F69',
        keyboard: '#DCE0E8',
        key: '#FFFFFF',
        keyFunction: '#CCD0DA',
        keyShadow: '#9CA0B0',
        keyArmed: '#ECE2FC',
        primaryBorder: 'transparent',
        segmentTrack: '#E6E9EF',
        segmentThumb: '#FFFFFF',
      },
      terminal: {
        background: '#EFF1F5',
        foreground: '#4C4F69',
        cursor: '#DC8A78',
        cursorAccent: '#EFF1F5',
        selectionBackground: '#ACB0BE99',
        black: '#5C5F77',
        red: '#D20F39',
        green: '#40A02B',
        yellow: '#DF8E1D',
        blue: '#1E66F5',
        magenta: '#EA76CB',
        cyan: '#179299',
        white: '#ACB0BE',
        brightBlack: '#6C6F85',
        brightRed: '#D20F39',
        brightGreen: '#40A02B',
        brightYellow: '#DF8E1D',
        brightBlue: '#1E66F5',
        brightMagenta: '#EA76CB',
        brightCyan: '#179299',
        brightWhite: '#BCC0CC',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.5,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 0.9,
        labelWeight: 600,
        radius: {
          small: 8,
          medium: 12,
          large: 16,
          pill: 999,
          key: 7,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(43, 33, 22, 0.15)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'rounded',
      },
    },
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    family: 'Terminal',
    description: 'Retro groove: warm earth tones, orange accent, medium contrast.',
    dark: {
      colors: {
        background: '#282828',
        backgroundElement: '#32302F',
        backgroundSelected: '#3C3836',
        backgroundRaised: '#45403D',
        border: '#504945',
        text: '#EBDBB2',
        textSecondary: '#BDAE93',
        primary: '#FE8019',
        onPrimary: '#282828',
        primaryMuted: '#4A3420',
        primaryText: '#FE8019',
        success: '#B8BB26',
        warning: '#FABD2F',
        danger: '#FF7262',
        attention: '#FE8019',
        shadow: '#000000',
        keyboard: '#1D2021',
        key: '#3C3836',
        keyFunction: '#32302F',
        keyShadow: '#141617',
        keyArmed: '#4A3420',
        primaryBorder: 'transparent',
        segmentTrack: '#32302F',
        segmentThumb: '#45403D',
      },
      terminal: {
        background: '#282828',
        foreground: '#EBDBB2',
        cursor: '#EBDBB2',
        cursorAccent: '#282828',
        selectionBackground: '#665C5499',
        black: '#282828',
        red: '#CC241D',
        green: '#98971A',
        yellow: '#D79921',
        blue: '#458588',
        magenta: '#B16286',
        cyan: '#689D6A',
        white: '#A89984',
        brightBlack: '#928374',
        brightRed: '#FB4934',
        brightGreen: '#B8BB26',
        brightYellow: '#FABD2F',
        brightBlue: '#83A598',
        brightMagenta: '#D3869B',
        brightCyan: '#8EC07C',
        brightWhite: '#EBDBB2',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.5,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 0.9,
        labelWeight: 600,
        radius: {
          small: 8,
          medium: 12,
          large: 16,
          pill: 999,
          key: 7,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(0, 0, 0, 0.6)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'outlined',
      },
    },
    light: {
      colors: {
        background: '#FBF1C7',
        backgroundElement: '#F9F5D7',
        backgroundSelected: '#EBDBB2',
        backgroundRaised: '#F9F5D7',
        border: '#D5C4A1',
        text: '#3C3836',
        textSecondary: '#665C54',
        primary: '#AF3A03',
        onPrimary: '#F9F5D7',
        primaryMuted: '#F3DCB7',
        primaryText: '#AF3A03',
        success: '#79740E',
        warning: '#9A6410',
        danger: '#9D0006',
        attention: '#AF3A03',
        shadow: '#3C3836',
        keyboard: '#EBDBB2',
        key: '#F9F5D7',
        keyFunction: '#D5C4A1',
        keyShadow: '#A89984',
        keyArmed: '#F3DCB7',
        primaryBorder: 'transparent',
        segmentTrack: '#EBDBB2',
        segmentThumb: '#F9F5D7',
      },
      terminal: {
        background: '#FBF1C7',
        foreground: '#3C3836',
        cursor: '#3C3836',
        cursorAccent: '#FBF1C7',
        selectionBackground: '#D5C4A199',
        black: '#FBF1C7',
        red: '#CC241D',
        green: '#98971A',
        yellow: '#D79921',
        blue: '#458588',
        magenta: '#B16286',
        cyan: '#689D6A',
        white: '#7C6F64',
        brightBlack: '#928374',
        brightRed: '#9D0006',
        brightGreen: '#79740E',
        brightYellow: '#B57614',
        brightBlue: '#076678',
        brightMagenta: '#8F3F71',
        brightCyan: '#427B58',
        brightWhite: '#3C3836',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.5,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 0.9,
        labelWeight: 600,
        radius: {
          small: 8,
          medium: 12,
          large: 16,
          pill: 999,
          key: 7,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(43, 33, 22, 0.15)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'outlined',
      },
    },
  },
  {
    id: 'solarized',
    name: 'Solarized',
    family: 'Terminal',
    description: 'Ethan Schoonover’s precision palette, cyan accent, the same hues in both modes.',
    dark: {
      colors: {
        background: '#002B36',
        backgroundElement: '#073642',
        backgroundSelected: '#0D4250',
        backgroundRaised: '#104552',
        border: '#124C5B',
        text: '#EEE8D5',
        textSecondary: '#93A1A1',
        primary: '#2AA198',
        onPrimary: '#002B36',
        primaryMuted: '#0B4A4A',
        primaryText: '#35B5AB',
        success: '#859900',
        warning: '#B58900',
        danger: '#F2706B',
        attention: '#E8833A',
        shadow: '#000000',
        keyboard: '#00222B',
        key: '#0D4250',
        keyFunction: '#073642',
        keyShadow: '#001A21',
        keyArmed: '#0B4A4A',
        primaryBorder: 'transparent',
        segmentTrack: '#073642',
        segmentThumb: '#104552',
      },
      terminal: {
        background: '#002B36',
        foreground: '#839496',
        cursor: '#93A1A1',
        cursorAccent: '#002B36',
        selectionBackground: '#93A1A133',
        black: '#073642',
        red: '#DC322F',
        green: '#859900',
        yellow: '#B58900',
        blue: '#268BD2',
        magenta: '#D33682',
        cyan: '#2AA198',
        white: '#EEE8D5',
        brightBlack: '#586E75',
        brightRed: '#CB4B16',
        brightGreen: '#586E75',
        brightYellow: '#657B83',
        brightBlue: '#839496',
        brightMagenta: '#6C71C4',
        brightCyan: '#93A1A1',
        brightWhite: '#FDF6E3',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.5,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 0.9,
        labelWeight: 600,
        radius: {
          small: 8,
          medium: 12,
          large: 16,
          pill: 999,
          key: 7,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(0, 0, 0, 0.6)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'outlined',
      },
    },
    light: {
      colors: {
        background: '#FDF6E3',
        backgroundElement: '#FFFCF4',
        backgroundSelected: '#EEE8D5',
        backgroundRaised: '#FFFCF4',
        border: '#E3DCC6',
        text: '#073642',
        textSecondary: '#586E75',
        primary: '#1D72B0',
        onPrimary: '#FDF6E3',
        primaryMuted: '#E3EEF3',
        primaryText: '#1D72B0',
        success: '#5F7000',
        warning: '#8A6800',
        danger: '#C22A27',
        attention: '#B8430F',
        shadow: '#073642',
        keyboard: '#EEE8D5',
        key: '#FFFCF4',
        keyFunction: '#DDD6BF',
        keyShadow: '#A8A18C',
        keyArmed: '#F6E2CF',
        primaryBorder: 'transparent',
        segmentTrack: '#EEE8D5',
        segmentThumb: '#FFFCF4',
      },
      terminal: {
        background: '#FDF6E3',
        foreground: '#657B83',
        cursor: '#586E75',
        cursorAccent: '#FDF6E3',
        selectionBackground: '#586E7526',
        black: '#073642',
        red: '#DC322F',
        green: '#859900',
        yellow: '#B58900',
        blue: '#268BD2',
        magenta: '#D33682',
        cyan: '#2AA198',
        white: '#EEE8D5',
        brightBlack: '#002B36',
        brightRed: '#CB4B16',
        brightGreen: '#586E75',
        brightYellow: '#657B83',
        brightBlue: '#839496',
        brightMagenta: '#6C71C4',
        brightCyan: '#93A1A1',
        brightWhite: '#FDF6E3',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.5,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 0.9,
        labelWeight: 600,
        radius: {
          small: 8,
          medium: 12,
          large: 16,
          pill: 999,
          key: 7,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 8px 24px rgba(43, 33, 22, 0.15)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'outlined',
      },
    },
  },
  {
    id: 'graphite',
    name: 'Graphite',
    family: 'Modern',
    description: 'Neutral graphite, larger radii, soft elevation, a signal-lime accent.',
    dark: {
      colors: {
        background: '#0C0D0E',
        backgroundElement: '#151618',
        backgroundSelected: '#1D1F22',
        backgroundRaised: '#222428',
        border: '#26282C',
        text: '#F2F3F4',
        textSecondary: '#9A9EA6',
        primary: '#C4F135',
        onPrimary: '#0C0D0E',
        primaryMuted: '#232B10',
        primaryText: '#C4F135',
        success: '#4ADE80',
        warning: '#FBBF24',
        danger: '#F87171',
        attention: '#C4F135',
        shadow: '#000000',
        keyboard: '#101113',
        key: '#2A2C30',
        keyFunction: '#1C1E21',
        keyShadow: '#050506',
        keyArmed: '#2A3412',
        primaryBorder: 'transparent',
        segmentTrack: '#151618',
        segmentThumb: '#222428',
      },
      terminal: {
        background: '#0C0D0E',
        foreground: '#E3E5E8',
        cursor: '#C4F135',
        cursorAccent: '#0C0D0E',
        selectionBackground: '#C4F13533',
        black: '#24262A',
        red: '#FF6B6B',
        green: '#8EE05A',
        yellow: '#F5C84C',
        blue: '#6AA9FF',
        magenta: '#D48CFF',
        cyan: '#4FD6D6',
        white: '#C8CCD2',
        brightBlack: '#6E737B',
        brightRed: '#FF8F8F',
        brightGreen: '#B5F27A',
        brightYellow: '#FFDB7D',
        brightBlue: '#94C2FF',
        brightMagenta: '#E4B0FF',
        brightCyan: '#85E8E8',
        brightWhite: '#F5F6F7',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.8,
        displayCase: 'none',
        labelCase: 'none',
        labelTracking: 0,
        labelWeight: 600,
        radius: {
          small: 10,
          medium: 14,
          large: 20,
          pill: 999,
          key: 8,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: '0 1px 0 rgba(255, 255, 255, 0.03) inset, 0 8px 24px rgba(0, 0, 0, 0.28)',
        shadowFloat: '0 16px 40px rgba(0, 0, 0, 0.55)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.97,
        pressShift: 0,
        iconStyle: 'rounded',
      },
    },
    light: {
      colors: {
        background: '#F7F7F6',
        backgroundElement: '#FFFFFF',
        backgroundSelected: '#EEEEEC',
        backgroundRaised: '#FFFFFF',
        border: '#E4E4E1',
        text: '#111213',
        textSecondary: '#5D6066',
        primary: '#B5E61D',
        onPrimary: '#111213',
        primaryMuted: '#EEF8D0',
        primaryText: '#3D7400',
        success: '#15803D',
        warning: '#A16207',
        danger: '#DC2626',
        attention: '#3D7400',
        shadow: '#111213',
        keyboard: '#E3E4E1',
        key: '#FFFFFF',
        keyFunction: '#D4D5D1',
        keyShadow: '#A0A29C',
        keyArmed: '#EEF8D0',
        primaryBorder: 'transparent',
        segmentTrack: '#EEEEEC',
        segmentThumb: '#FFFFFF',
      },
      terminal: {
        background: '#F7F7F6',
        foreground: '#1A1B1D',
        cursor: '#3D7400',
        cursorAccent: '#F7F7F6',
        selectionBackground: '#B5E61D55',
        black: '#1A1B1D',
        red: '#C62828',
        green: '#2E7D1F',
        yellow: '#8A6100',
        blue: '#1F5FCC',
        magenta: '#9B3FC4',
        cyan: '#0E7C86',
        white: '#6C6F74',
        brightBlack: '#80838A',
        brightRed: '#D63A3A',
        brightGreen: '#3A8F26',
        brightYellow: '#9B6E00',
        brightBlue: '#2F6FE0',
        brightMagenta: '#A74CCF',
        brightCyan: '#0B8793',
        brightWhite: '#8A8D92',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'geist',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: -0.8,
        displayCase: 'none',
        labelCase: 'none',
        labelTracking: 0,
        labelWeight: 600,
        radius: {
          small: 10,
          medium: 14,
          large: 20,
          pill: 999,
          key: 8,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: '0 1px 2px rgba(16, 18, 20, 0.05), 0 6px 20px rgba(16, 18, 20, 0.05)',
        shadowFloat: '0 16px 40px rgba(16, 18, 20, 0.14)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.97,
        pressShift: 0,
        iconStyle: 'rounded',
      },
    },
  },
  {
    id: 'orbit',
    name: 'Orbit',
    family: 'Futuristic',
    description:
      'Flight-deck HUD: squared corners, tracked uppercase labels, cyan instruments, orange for a human.',
    dark: {
      colors: {
        background: '#060A10',
        backgroundElement: '#0B121B',
        backgroundSelected: '#111B27',
        backgroundRaised: '#142030',
        border: '#1B2A3B',
        text: '#DBE9F5',
        textSecondary: '#7F97AD',
        primary: '#3DE0FF',
        onPrimary: '#021018',
        primaryMuted: '#0B2A36',
        primaryText: '#3DE0FF',
        success: '#2EF2A0',
        warning: '#FFCC33',
        danger: '#FF4D6A',
        attention: '#FF9F1C',
        shadow: '#000000',
        keyboard: '#04070C',
        key: '#142030',
        keyFunction: '#0C1621',
        keyShadow: '#000000',
        keyArmed: '#0B2A36',
        primaryBorder: 'transparent',
        segmentTrack: '#0B121B',
        segmentThumb: '#142030',
      },
      terminal: {
        background: '#060A10',
        foreground: '#CFE3F2',
        cursor: '#3DE0FF',
        cursorAccent: '#060A10',
        selectionBackground: '#3DE0FF33',
        black: '#142030',
        red: '#FF4D6A',
        green: '#2EF2A0',
        yellow: '#FFCC33',
        blue: '#4D9DFF',
        magenta: '#B98CFF',
        cyan: '#3DE0FF',
        white: '#A9BFD2',
        brightBlack: '#5A7189',
        brightRed: '#FF8094',
        brightGreen: '#7AF7C2',
        brightYellow: '#FFDD75',
        brightBlue: '#85BCFF',
        brightMagenta: '#D2B3FF',
        brightCyan: '#8AEDFF',
        brightWhite: '#EEF6FC',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'chakraPetch',
          label: 'geistMono',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: 0.5,
        displayCase: 'uppercase',
        labelCase: 'uppercase',
        labelTracking: 2,
        labelWeight: 500,
        radius: {
          small: 2,
          medium: 4,
          large: 6,
          pill: 2,
          key: 3,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 0 0 1px rgba(61, 224, 255, 0.25), 0 12px 32px rgba(0, 0, 0, 0.6)',
        shadowControl: 'none',
        glowPrimary: '0 0 16px rgba(61, 224, 255, 0.35)',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'sharp',
      },
    },
    light: {
      colors: {
        background: '#EEF2F6',
        backgroundElement: '#F9FBFD',
        backgroundSelected: '#E1E8EF',
        backgroundRaised: '#FFFFFF',
        border: '#CDD8E3',
        text: '#0B1824',
        textSecondary: '#4B5F72',
        primary: '#00758F',
        onPrimary: '#FFFFFF',
        primaryMuted: '#D8EEF3',
        primaryText: '#00758F',
        success: '#0A7D55',
        warning: '#8C6500',
        danger: '#C8203F',
        attention: '#A85400',
        shadow: '#0B1824',
        keyboard: '#DFE6EE',
        key: '#F9FBFD',
        keyFunction: '#CBD5E0',
        keyShadow: '#95A3B3',
        keyArmed: '#D8EEF3',
        primaryBorder: 'transparent',
        segmentTrack: '#E1E8EF',
        segmentThumb: '#F9FBFD',
      },
      terminal: {
        background: '#EEF2F6',
        foreground: '#10202E',
        cursor: '#00758F',
        cursorAccent: '#EEF2F6',
        selectionBackground: '#00758F26',
        black: '#10202E',
        red: '#C8203F',
        green: '#0A7D55',
        yellow: '#8C6500',
        blue: '#1F5FCC',
        magenta: '#7A3FC4',
        cyan: '#00758F',
        white: '#5D6F80',
        brightBlack: '#72869A',
        brightRed: '#D63A55',
        brightGreen: '#0D8F62',
        brightYellow: '#9C7200',
        brightBlue: '#2F6FE0',
        brightMagenta: '#8A4FD4',
        brightCyan: '#0086A3',
        brightWhite: '#8295A8',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'chakraPetch',
          label: 'geistMono',
          mono: 'geistMono',
        },
        displayWeight: 600,
        displayTracking: 0.5,
        displayCase: 'uppercase',
        labelCase: 'uppercase',
        labelTracking: 2,
        labelWeight: 500,
        radius: {
          small: 2,
          medium: 4,
          large: 6,
          pill: 2,
          key: 3,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 0 0 1px rgba(0, 117, 143, 0.25), 0 12px 32px rgba(11, 24, 36, 0.12)',
        shadowControl: 'none',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'sharp',
      },
    },
  },
  {
    id: 'neon',
    name: 'Neon',
    family: 'Neon',
    description:
      'Night-city signage: hot magenta tubes, cyan for attention, everything live glows.',
    dark: {
      colors: {
        background: '#0B0710',
        backgroundElement: '#140D1C',
        backgroundSelected: '#1E1429',
        backgroundRaised: '#241834',
        border: '#2C1F3D',
        text: '#F6EEFE',
        textSecondary: '#A996BF',
        primary: '#FF3DBB',
        onPrimary: '#1A0012',
        primaryMuted: '#3A1031',
        primaryText: '#FF5CC6',
        success: '#3DFFB5',
        warning: '#FFE14A',
        danger: '#FF4F5E',
        attention: '#23E5FF',
        shadow: '#000000',
        keyboard: '#08050C',
        key: '#241834',
        keyFunction: '#160F20',
        keyShadow: '#000000',
        keyArmed: '#3A1031',
        primaryBorder: 'transparent',
        segmentTrack: '#140D1C',
        segmentThumb: '#241834',
      },
      terminal: {
        background: '#0B0710',
        foreground: '#EADCF7',
        cursor: '#FF3DBB',
        cursorAccent: '#0B0710',
        selectionBackground: '#FF3DBB40',
        black: '#241834',
        red: '#FF4F5E',
        green: '#3DFFB5',
        yellow: '#FFE14A',
        blue: '#5C8DFF',
        magenta: '#FF3DBB',
        cyan: '#23E5FF',
        white: '#CBB8E0',
        brightBlack: '#6F5A8A',
        brightRed: '#FF8590',
        brightGreen: '#85FFD0',
        brightYellow: '#FFF08A',
        brightBlue: '#93B4FF',
        brightMagenta: '#FF85D6',
        brightCyan: '#7FF0FF',
        brightWhite: '#FBF5FF',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'tiltNeon',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 400,
        displayTracking: 0,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 1.4,
        labelWeight: 600,
        radius: {
          small: 10,
          medium: 14,
          large: 18,
          pill: 999,
          key: 8,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 0 0 1px rgba(255, 61, 187, 0.3), 0 12px 36px rgba(0, 0, 0, 0.65)',
        shadowControl: 'none',
        glowPrimary: '0 0 0 1px #FF3DBB, 0 0 18px rgba(255, 61, 187, 0.55)',
        textGlow: {
          color: 'rgba(255, 61, 187, 0.7)',
          radius: 10,
        },
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'rounded',
      },
    },
    light: {
      colors: {
        background: '#FDF6FB',
        backgroundElement: '#FFFFFF',
        backgroundSelected: '#F6E6F1',
        backgroundRaised: '#FFFFFF',
        border: '#EFD5E7',
        text: '#1F0A1A',
        textSecondary: '#6E4F66',
        primary: '#D4007F',
        onPrimary: '#FFFFFF',
        primaryMuted: '#FDE0F1',
        primaryText: '#C20074',
        success: '#00875A',
        warning: '#946200',
        danger: '#D11A3A',
        attention: '#0077A8',
        shadow: '#6B0040',
        keyboard: '#F3E1ED',
        key: '#FFFFFF',
        keyFunction: '#E7CFDF',
        keyShadow: '#C79DB9',
        keyArmed: '#FDE0F1',
        primaryBorder: 'transparent',
        segmentTrack: '#F6E6F1',
        segmentThumb: '#FFFFFF',
      },
      terminal: {
        background: '#FDF6FB',
        foreground: '#24101F',
        cursor: '#D4007F',
        cursorAccent: '#FDF6FB',
        selectionBackground: '#D4007F26',
        black: '#24101F',
        red: '#D11A3A',
        green: '#00875A',
        yellow: '#946200',
        blue: '#2950D6',
        magenta: '#C20074',
        cyan: '#0077A8',
        white: '#6E5A69',
        brightBlack: '#8A7586',
        brightRed: '#E0304F',
        brightGreen: '#009966',
        brightYellow: '#A66E00',
        brightBlue: '#3B62E6',
        brightMagenta: '#D4007F',
        brightCyan: '#0088BF',
        brightWhite: '#9A8695',
      },
      shape: {
        fonts: {
          ui: 'geist',
          display: 'tiltNeon',
          label: 'geist',
          mono: 'geistMono',
        },
        displayWeight: 400,
        displayTracking: 0,
        displayCase: 'none',
        labelCase: 'uppercase',
        labelTracking: 1.4,
        labelWeight: 600,
        radius: {
          small: 10,
          medium: 14,
          large: 18,
          pill: 999,
          key: 8,
          dot: 999,
        },
        borderWidth: 1,
        borderWidthStrong: 1.5,
        shadowCard: 'none',
        shadowFloat: '0 12px 36px rgba(107, 0, 64, 0.16)',
        shadowControl: 'none',
        glowPrimary: '0 0 0 1px #D4007F, 0 6px 18px rgba(212, 0, 127, 0.28)',
        textGlow: null,
        pressScale: 0.985,
        pressShift: 0,
        iconStyle: 'rounded',
      },
    },
  },
  {
    id: 'concrete',
    name: 'Concrete',
    family: 'Brutalist',
    description: 'Raw: square corners, 2px ink rules, hard offset shadows, one safety-yellow fill.',
    dark: {
      colors: {
        background: '#0E0E0E',
        backgroundElement: '#161616',
        backgroundSelected: '#262626',
        backgroundRaised: '#1C1C1C',
        border: '#F2F2F2',
        text: '#F2F2F2',
        textSecondary: '#B3B3B3',
        primary: '#FFE500',
        onPrimary: '#000000',
        primaryMuted: '#332E00',
        primaryText: '#FFE500',
        success: '#00E05A',
        warning: '#FF9500',
        danger: '#FF3B30',
        attention: '#FFE500',
        shadow: '#F2F2F2',
        keyboard: '#000000',
        key: '#1C1C1C',
        keyFunction: '#0E0E0E',
        keyShadow: '#F2F2F2',
        keyArmed: '#332E00',
        primaryBorder: '#F2F2F2',
        segmentTrack: '#161616',
        segmentThumb: '#1C1C1C',
      },
      terminal: {
        background: '#0E0E0E',
        foreground: '#F2F2F2',
        cursor: '#FFE500',
        cursorAccent: '#0E0E0E',
        selectionBackground: '#FFE50055',
        black: '#262626',
        red: '#FF3B30',
        green: '#00E05A',
        yellow: '#FFE500',
        blue: '#4D7CFF',
        magenta: '#FF4DD2',
        cyan: '#00D9E0',
        white: '#CCCCCC',
        brightBlack: '#7A7A7A',
        brightRed: '#FF6E66',
        brightGreen: '#5CFF9A',
        brightYellow: '#FFF066',
        brightBlue: '#85A5FF',
        brightMagenta: '#FF8AE2',
        brightCyan: '#66ECF0',
        brightWhite: '#FFFFFF',
      },
      shape: {
        fonts: {
          ui: 'plexMono',
          display: 'plexMono',
          label: 'plexMono',
          mono: 'plexMono',
        },
        displayWeight: 700,
        displayTracking: -1,
        displayCase: 'uppercase',
        labelCase: 'uppercase',
        labelTracking: 1,
        labelWeight: 700,
        radius: {
          small: 0,
          medium: 0,
          large: 0,
          pill: 0,
          key: 0,
          dot: 0,
        },
        borderWidth: 2,
        borderWidthStrong: 3,
        shadowCard: '4px 4px 0 #F2F2F2',
        shadowFloat: '6px 6px 0 #F2F2F2',
        shadowControl: '3px 3px 0 #F2F2F2',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 1,
        pressShift: 2,
        iconStyle: 'sharp',
      },
    },
    light: {
      colors: {
        background: '#EFEDE8',
        backgroundElement: '#FFFFFF',
        backgroundSelected: '#E0DDD6',
        backgroundRaised: '#FFFFFF',
        border: '#000000',
        text: '#000000',
        textSecondary: '#4A4A4A',
        primary: '#FFE500',
        onPrimary: '#000000',
        primaryMuted: '#FFF7B3',
        primaryText: '#000000',
        success: '#00873C',
        warning: '#B35C00',
        danger: '#D70015',
        attention: '#CC2200',
        shadow: '#000000',
        keyboard: '#E0DDD6',
        key: '#FFFFFF',
        keyFunction: '#EFEDE8',
        keyShadow: '#000000',
        keyArmed: '#FFF7B3',
        primaryBorder: '#000000',
        segmentTrack: '#E0DDD6',
        segmentThumb: '#FFFFFF',
      },
      terminal: {
        background: '#EFEDE8',
        foreground: '#000000',
        cursor: '#000000',
        cursorAccent: '#EFEDE8',
        selectionBackground: '#FFE50099',
        black: '#000000',
        red: '#CC1100',
        green: '#00732F',
        yellow: '#8A6A00',
        blue: '#0033CC',
        magenta: '#A3007D',
        cyan: '#00707A',
        white: '#555555',
        brightBlack: '#6B6B6B',
        brightRed: '#E02A1A',
        brightGreen: '#008A3A',
        brightYellow: '#9E7A00',
        brightBlue: '#1F4FE0',
        brightMagenta: '#B8168F',
        brightCyan: '#00808A',
        brightWhite: '#7A7A7A',
      },
      shape: {
        fonts: {
          ui: 'plexMono',
          display: 'plexMono',
          label: 'plexMono',
          mono: 'plexMono',
        },
        displayWeight: 700,
        displayTracking: -1,
        displayCase: 'uppercase',
        labelCase: 'uppercase',
        labelTracking: 1,
        labelWeight: 700,
        radius: {
          small: 0,
          medium: 0,
          large: 0,
          pill: 0,
          key: 0,
          dot: 0,
        },
        borderWidth: 2,
        borderWidthStrong: 3,
        shadowCard: '4px 4px 0 #000000',
        shadowFloat: '6px 6px 0 #000000',
        shadowControl: '3px 3px 0 #000000',
        glowPrimary: 'none',
        textGlow: null,
        pressScale: 1,
        pressShift: 2,
        iconStyle: 'sharp',
      },
    },
  },
];

export function isAppThemeId(value: unknown): value is AppThemeId {
  return APP_THEME_IDS.includes(value as AppThemeId);
}

/** The variant for a theme in light or dark mode; unknown ids get Flare's. */
export function appTheme(id: AppThemeId, mode: 'light' | 'dark'): ThemeVariant {
  const theme = APP_THEMES.find((candidate) => candidate.id === id) ?? APP_THEMES[0];
  return theme[mode];
}
